fixup! testing workaround

diff --git a/deps/compose.template b/deps/compose.template
--- a/deps/compose.template
+++ b/deps/compose.template
@@ -111,15 +111,16 @@ services:
 
   snos_block_zero_workaround:
     image: mongo
+    container_name: workaround
     depends_on:
       bootstrapper_l2:
         condition: service_completed_successfully
-    entrypoint: entrypoint: [ "bash", "-c", "
-                            echo 'Checking init script...';
-                            ls -l /init.js || echo 'File not found';
-                            cat /init.js || echo 'Cannot read file';
-                            mongosh --host mongodb --eval 'load(\"/init.js\")';
-                          " ]
+    entrypoint: [ "bash", "-c", "
+                  echo 'Checking init script...';
+                  ls -l /init.js || echo 'File not found';
+                  cat /init.js || echo 'Cannot read file';
+                  mongosh --host mongodb --eval 'load(\"/init.js\")';
+                " ]
     volumes:
       - ./block_zero_workaround.js:/init.js
 
