Global config (#31)
* add some deps

* use serde_yaml instead of serde_yml

* initial global config logic

* improve global config

* add madara and bootstrapper config file interface

* propage config to bootstrapper

* propage config to madara

* propage config to pathfinder

* propage config to orchestrator and remaining services

* some fixes for changing ETH priv key

* remove debug msg

* add gas price from config file

* remove temporal madara_config folder

* add orchestrator max block to process

* update madara devnet preset with core contract and verifier addresses for local app chain

* add dep: toml

* intro function requires a message now

* rename variable

* init command to generate app chain config file

* improve create config file UI

* update readme

* improve keys related functions

* add interactively validation for input params

* perform input params validation

* modularize l1_config

* modularize eth_wallet

* modularize madara config

* modularize orchestrator config

* add cargo test to CI

* add default flag to global config

* add default_or_ask non-interactive method

* propagate default flag for init command

* add check in CI for init command

* create deps/data folder if it doesn't exist

diff --git a/.github/workflows/command_tests.yml b/.github/workflows/command_tests.yml
--- a/.github/workflows/command_tests.yml
+++ b/.github/workflows/command_tests.yml
@@ -27,3 +27,19 @@ jobs:
           toolchain: 1.81
       - name: Build cli
         run: cargo build
+      - name: Run tests
+        run: cargo test
+      # Generates a config file with default info and compare with local.toml 
+      - name: Compare default config
+        run: |
+          cargo run init --default
+          cargo install toml2json
+
+          # Convert both TOML files to JSON (this will ignore comments)
+          toml2json deps/data/my_custom_config.toml > generated_params.json
+          toml2json crates/madara/src/config/local.toml > reference_params.json
+
+          diff generated_params.json reference_params.json || {
+            echo "::error::Init command generated a configuration different than expected"
+            exit 1
+          }
